### ISSUE TITLE
Allow for calling `.download` without triggering a device reset

### ISSUE THREAD

**Issue by rukai** [dfu-rs/dfu-libusb#11]
I would like to be able to run download, set the write address elsewhere and then run download again.
My use case for this is flashing the firmware and a device config to separate locations without resetting in between.

**Comment by cecton** [comment]
It's possible to do in the development version. I will make a release in the next couple of days. If you want you can already use the development version by using the git repository's address in your Cargo.toml.

Then this is how you can achieve this:

1. First you need to get the DfuSync instance, then you call `into_inner()` on it to get back the IO. https://github.com/dfu-rs/dfu-core/blob/main/src/sync.rs#L41

2. Copy the code from DfuSync to make your own struct: https://github.com/dfu-rs/dfu-core/blob/main/src/sync.rs

In there you can see that the state machine requires the device to be reset. So the code calls `usb_reset`. But in your particular use case you can ignore that if you want.

```rust
                download::Step::UsbReset => {
                    log::trace!("Device reset");
                    // self.dfu.io.usb_reset()?; // nah don't reset
                    break;
                }
```

**Comment by cecton** [comment]
If you want for the release I will try also to improve the API so you don't need to do this "into_inner" step.

**Comment by rukai** [comment]
thankyou for the detailed response!
I'm more than happy to wait for the release as padding my firmware with 0's and then appending the config to that is working just fine for now.

**Comment by cecton** [comment]
> If you wait for the release I will try also to improve the API so you don't need to do this "into_inner" step.

hmm it's more complicated than I thought so I will give up on my promise here sorry :sweat: 

In the meantime I have release dfu-libusb 0.4.0 which has the function `into_inner()` that you need in order to write your own DfuSync implementation. I hope the explanations I gave were enough for you to make it work! Otherwise you just let me know and I'll produce some example (I'm just a bit lazy)

**Comment by sjoerdsimons** [comment]
> It's possible to do in the development version. I will make a release in the next couple of days. If you want you can already use the development version by using the git repository's address in your Cargo.toml.
> 
> Then this is how you can achieve this:
> 
> 1. First you need to get the DfuSync instance, then you call `into_inner()` on it to get back the IO. https://github.com/dfu-rs/dfu-core/blob/main/src/sync.rs#L41
> 2. Copy the code from DfuSync to make your own struct: https://github.com/dfu-rs/dfu-core/blob/main/src/sync.rs
> 
> In there you can see that the state machine requires the device to be reset. So the code calls `usb_reset`. But in your particular use case you can ignore that if you want.

It only goes through that step if the device isn't indicating it's manifestation tolerant and indicates it won't detach it self..

Only devices that are manifestation tolerant in the first place support multiple downloads per definition as others won't go back to an idle state.

**Comment by cecton** [comment]
@rukai did you succeed with this?

**Comment by cecton** [comment]
Feel free to re-open if you still have issues
