### ISSUE TITLE
Unable to download into STM32 chips

### ISSUE THREAD

**Issue by beckler** [dfu-rs/dfu-libusb#4]
Not sure what's going on, or even how to begin to debug this.

I've basically re-implemented the example method, but I'm getting this error whenever I attempt to download into the device.
```rust
Err(DfuError("Device status is in error: Something went wrong, but the device does not know what it was."))
```

Here's the method I've re-implemented, but I don't think you'll find much useful info from it:
```rust
const USB_VENDOR_ID: u16 = 0x0483;
const USB_PRODUCT_DFU_ID: u16 = 0xDF11;
...
...
...
pub async fn install_binary<C: rusb::UsbContext>(
    device: Device<C>,
    binary_path: PathBuf,
    progress: Option<impl Fn(usize) + 'static>,
) -> Result<(), CommandError> {
    // open the binary file and get the file size
    let mut file = std::fs::File::open(binary_path).map_err(|e| {
        CommandError::IOError(format!("could not open firmware file: {}", e.to_string()))
    })?;
    let file_size = u32::try_from(
        file.seek(io::SeekFrom::End(0))
            .map_err(|e| CommandError::IOError(e.to_string()))?,
    )
    .map_err(|e| {
        CommandError::IOError(format!("the firmware file is too big: {}", e.to_string()))
    })?;
    file.seek(io::SeekFrom::Start(0))
        .map_err(|e| CommandError::IOError(e.to_string()))?;

    // open the DFU interface
    let mut dfu_iface = DfuLibusb::open(device.context(), USB_VENDOR_ID, USB_PRODUCT_DFU_ID, 0, 0)
        .map_err(|e| CommandError::DfuError(e.to_string()))?;

    // setup our progress bar - if available
    dfu_iface = if progress.is_some() {
        dfu_iface.with_progress(progress.unwrap())
    } else {
        dfu_iface
    };

    // PERFORM THE INSTALL
    dfu_iface
        .download(file, file_size)
        .map_err(|e| CommandError::DfuError(e.to_string()))
}
```

Open to any suggestions or recommendations because I'm out of ideas.

For full context, I normally flash the device with the following:
```
dfu-util -a 0 --dfuse-address 0x08000000 -D <filename>.bin
```

**Comment by cecton** [comment]
Unfortunately it's hard to tell... afaiu there are a lot of peculiarities among devices so it's possible we need to adapt the code in some way.

Let's try to reduce the scope a little bit. Can you try to flash your device using this project instead: https://crates.io/crates/dfu-flasher and see if it has the same issue? (dfu-libusb took inspiration on that project)

If possible for you, can you tell me the exact model of board you are using?

In the meantime I will try to improve the logging so we can have more information.

**Comment by cecton** [comment]
I added trace logs. Can you give it a try?

You need to add this to your `Cargo.toml` at the workspace root (your crate if you have only one crate):
```
[patch.crates-io]
dfu-core = { git = "https://github.com/cecton/dfu-core.git", branch = "improve-debug-logging" }
```

Then you need to add trace logs to your program. The easiest way is to add this to your crate's dependencies:

```
simplelog = "0.12"
```

And then add this early in the `fn main()`:

```
simplelog::SimpleLogger::init(simplelog::LevelFilter::Trace, Default::default()).unwrap();
```

**Comment by cecton** [comment]
(Don't hesitate to let me know if you have any issue)

**Comment by beckler** [comment]
WOAH! Dude, this is a high quality response that I did not expect!

- I attempted to install the `dfu-flasher` tool, but I threw a bunch of build errors. When I dug into it, it seems like the `usbapi` package is Linux only, which is probably my issue there as I'm on macOS.
- Particular chipset is STM32G491.
- It took a minute, but I got this library to start putting out the trace logs. I had to clone this repo and bump `dfu-core` to `0.3` to get the patch to take.

Here's the trace logs that I got from the device:
```shell
2022-07-25T07:54:12-04:00 - TRACE - Clear device status
2022-07-25T07:54:12-04:00 - TRACE - Received device status: 0e 00 00 00  0a 00
2022-07-25T07:54:12-04:00 - TRACE - Device status: ErrUnknown
2022-07-25T07:54:12-04:00 - TRACE - Poll timeout: 0
2022-07-25T07:54:12-04:00 - TRACE - Device state: DfuError
2022-07-25T07:54:12-04:00 - TRACE - Device i string: 0x0
```

**Comment by cecton** [comment]
Looking at the logs it's clear that the device didn't accept the initial "clear status". I will need to check the code of dfu-util to see if they do something special there. (I also took inspiration on that code I remember and that's how I know a lot of devices have peculiarities.)

Relevant part of the code `src/lib.rs`:

```rust
    /// Create a state machine to download the firmware into the device.
    pub fn download(
        &self,
        length: u32,
    ) -> Result<
        get_status::ClearStatus<'_, IO, get_status::GetStatus<'_, IO, download::Start<'_, IO>>>,
        Error,
    > {
        Ok(get_status::ClearStatus {
            dfu: self,
            chained_command: get_status::GetStatus {
                dfu: self,
                chained_command: download::Start {
                    dfu: self,
                    memory_layout: self.io.memory_layout(),
                    address: self.address,
                    end_pos: self.address.checked_add(length).ok_or(Error::NoSpaceLeft)?,
                },
            },
        })
    }
```

It reads as:
1. Clear status
2. Get status
3. Start download

I think the "clear status" step is optional or depend on the device. I will need to check that. You could also try on your own by deleting the ClearStatus from the return value (and type) and keep what is inside only.

> WOAH! This is a high quality response that I did not expect!

:trophy: Achievement unlocked!

Well tbh sometimes people hate me too so... but I try to do my best!

**Comment by beckler** [comment]
Alright!

So I forked `dfu-core` off of your logging branch and removed the initial "clear status" step, and that worked! 
I was able to flash successfully! 🙌 
Thank you!

To help some more, I ran dfu-util with the verbose flag, and this is the log I got back:
```
❯ dfu-util -v -a 0 --dfuse-address 0x08000000:leave -D install.bin
dfu-util 0.11

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

libusb version 1.0.25 (11692)
dfu-util: Warning: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release
Opening DFU capable USB device...
Device ID 0483:df11
Device DFU version 011a
DFU attributes: (0x0b) bitCanDnload bitCanUpload bitWillDetach
Detach timeout 255 ms
Claiming USB DFU Interface...
Setting Alternate Interface #0 ...
Determining device status...
DFU state(2) = dfuIDLE, status(0) = No error condition is present
DFU mode device DFU version 011a
Device returned transfer size 1024
DfuSe interface name: "Internal Flash   "
Memory segment at 0x08000000 256 x 2048 = 524288 (rew)
Downloading element to address = 0x08000000, size = 226024
Erasing page size 2048 at address 0x08000000, page starting at 0x08000000
...
...[redacted because it's likely not useful]...
...
 Download from image offset 00037000 to memory 08037000-080372e7, size 744
File downloaded successfully

```

I followed the logs through `dfu-util` and it looked like it only cleared the status if there was an error in the initial status. HOWEVER, my C/C++ skills are not great by any means... so please take last statement with a grain of salt 🙈. 
I'm not able to link the lines, but when I followed the logs, this is the block I got to around the status: (v0.11 main.c L630-679)

```c
status_again:
	printf("Determining device status...\n");
	ret = dfu_get_status(dfu_root, &status );
	if (ret < 0) {
		errx(EX_IOERR, "error get_status: %s", libusb_error_name(ret));
	}
	printf("DFU state(%u) = %s, status(%u) = %s\n", status.bState,
	       dfu_state_to_string(status.bState), status.bStatus,
	       dfu_status_to_string(status.bStatus));

	milli_sleep(status.bwPollTimeout);

	switch (status.bState) {
	case DFU_STATE_appIDLE:
	case DFU_STATE_appDETACH:
		errx(EX_PROTOCOL, "Device still in Run-Time Mode!");
		break;
	case DFU_STATE_dfuERROR:
		printf("Clearing status\n");
		if (dfu_clear_status(dfu_root->dev_handle, dfu_root->interface) < 0) {
			errx(EX_IOERR, "error clear_status");
		}
		goto status_again;
		break;
	case DFU_STATE_dfuDNLOAD_IDLE:
	case DFU_STATE_dfuUPLOAD_IDLE:
		printf("Aborting previous incomplete transfer\n");
		if (dfu_abort(dfu_root->dev_handle, dfu_root->interface) < 0) {
			errx(EX_IOERR, "can't send DFU_ABORT");
		}
		goto status_again;
		break;
	case DFU_STATE_dfuIDLE:
	default:
		break;
	}

	if (DFU_STATUS_OK != status.bStatus ) {
		printf("WARNING: DFU Status: '%s'\n",
			dfu_status_to_string(status.bStatus));
		/* Clear our status & try again. */
		if (dfu_clear_status(dfu_root->dev_handle, dfu_root->interface) < 0)
			errx(EX_IOERR, "USB communication error");
		if (dfu_get_status(dfu_root, &status) < 0)
			errx(EX_IOERR, "USB communication error");
		if (DFU_STATUS_OK != status.bStatus)
			errx(EX_PROTOCOL, "Status is not OK: %d", status.bStatus);

		milli_sleep(status.bwPollTimeout);
	}
```

I'm not sure what to do with this information. I want to help make these libraries better, but at the same time, I have no idea how else to help other than giving you as much information as I can!

**Comment by cecton** [comment]
> I'm not sure what to do with this information. I want to help make these libraries better, but at the same time, I have no idea how else to help other than giving you as much information as I can!

That's really really helpful thanks!! xD 75% of the work is done thanks to you!

You don't "have" to do anything really, you came asking for help, not to make a contribution. Though with all the work you already did I think you should actually make a PR at some point so your contribution is recognized.

**IF** (and only if) you want to do it yourself:

I think we have almost everything we need here: we know the clearing status was the problem and the likely fix is to conditionally do the status clearing like they do in dfu-util. I can make a PR in the following days but if you want to do it yourself, you need to put back the `ClearStatus` in the type and in the code and wrap it around another `GetStatus`. Then you need to add an impl `ChainedCommand` on ClearStatus so it will only clears the status if the previous status was "Error". :warning: You have to move the code from `pub fn clear()` to the "chain" method you're making. (Don't keep the `pub fn clear()`!)

It should look like this:

```rust
impl<'dfu, IO: DfuIo, T> ChainedCommand for ClearStatus<'dfu, IO, T> {
    type Arg = get_status::GetStatusMessage;
    type Into = Result<(T, IO::Write), IO::Error>;

    fn chain(
        self,
        get_status::GetStatusMessage {
            status: _,
            poll_timeout: _,
            state,
            index: _,
        }: Self::Arg,
    ) -> Self::Into {
        if state == State::DfuError {
            // clear status
        } else {
            // return the chained command without res
        }
    }
}
```

After that, you will also need to adapt the code in `sync.rs` to accommodate with the change. That part should be pretty straightforward because since it's a state machine, the compiler will force you to take the right path.

**Comment by cecton** [comment]
I have done the change.

Please test and re-open this issue if it's not fixed.

**Comment by cecton** [comment]
You can test with dfu-libusb 0.3.0 I just released

**Comment by beckler** [comment]
Hey @cecton!
Sorry I'm just now getting back around to this. I updated to deps to the latest version and they work flawlessly!
Thank you again!

**Comment by cecton** [comment]
Noice! I'm glad it worked!
